### ISSUE TITLE
Improve display of long-term graph

### ISSUE THREAD

**Issue by rixx** [blinry/nom#14]
My nom history goes back nearly five years at this point (whee! and thank you as always for this tool). Sometimes I want to see my overall history, which takes a while to render (absolutely fine) and looks generally really well except that the time scale isn't readable at all:
![2022-10-20T11:22:55+02:00](https://user-images.githubusercontent.com/2657547/196910119-35b7513a-9858-45d6-b95f-37fd70de19b4.png)

My current solution is to manually append this stylesheet, hiding every marker except every 3rd or 4th:

```css
g[text-anchor=middle] {
  display: none;
}
g:nth-of-type(4n) g[text-anchor=middle] {
  display: block;
}
```

It would probably be the easiest to either drop the labels during rendering, or to hide them immediately (`color=white` would do it). 

For reference, on my display, Every 3rd entry worked fine for up to ~40-44 months, but 4 years were already better with every 4th entry.
